---
extends: default

document-start: disable  # Don't require --- at start of file

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces:
    level: error

  # Empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Document end
  document-end: disable

  # Empty values
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

  # Quoted strings
  quoted-strings:
    quote-type: any
    required: only-when-needed
    extra-allowed: ["'", '"']

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Indentation of sequence values
  indents:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

ignore: |
  **/node_modules/**
  **/dist/**
  **/coverage/**
  **/build/**
  **/.github/**/*.md
