name: Workflow Hygiene

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v1
        with:
          config-file: .github/actionlint.yml

  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v4
        with:
          config_file: .yamllint.yml
          file_or_dir: .
          strict: true

  dependabot:
    name: Check Dependabot Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Dependabot config
        run: |
          if [ ! -f .github/dependabot.yml ]; then
            echo "::warning::No Dependabot configuration found. Consider adding one to keep dependencies up to date."
          fi
